language: php

php:
  - 7.1
  - 7.2
  - 7.3

before_script:
    - curl -s http://getcomposer.org/installer | php
    - php composer.phar install

script:
    - ./vendor/bin/phpunit --coverage-clover ./build/logs/clover.xml
    - ./vendor/bin/phpcs -v --standard=PSR2 --ignore=PrerenderBundle/vendor .

after_success:
    - php vendor/bin/coveralls -v
